import Head from "next/head";
import BtnBack from "./btnBack";

export default function Layout({ children, btnBack }) {
  return (
    <div className=" w-[1440px] xsm:w-full mx-auto ">
      <Head>
        <title>DevBase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/devbase.ico" />
      </Head>

      {btnBack ? (
        <div className="bg-black h-20 w-full flex-col items-center text-white font-robo font-bold xsm:text-[18px] pt-[26px] text-lg ">
          <div className="flex absolute pr-[5.5rem] ml-24">
            <BtnBack />
          </div>
          <div className="flex justify-center">Home</div>
        </div>
      ) : (
        <div className="bg-black h-20 w-full flex justify-center items-center text-white font-robo font-bold text-lg ">
          Home
        </div>
      )}

      <div className="font-robo">{children}</div>
    </div>
  );
}
